### ISSUE TITLE
 Are there any changes to nnunet?

### ISSUE THREAD

**Issue by ruifenggong** [JunMa11/ADAM2020#1]
for this project , are there any changes compare to the orgin nnunet?

**Comment by JunMa11** [comment]
Hi @ruifenggong ,

The direct answer is Yes.

However, honestly speaking, I do not remember them:- May be loss functions, GPU memory upper bound (I used V100 GPU), max channels...
**IT IS PROVIDED AS IS WITH.**

Sorry for the inconvenience.

Best,
Jun

**Comment by ruifenggong** [comment]
> Hi @ruifenggong ,
> 
> The direct answer is Yes.
> 
> However, honestly speaking, I do not remember them:- May be loss functions, GPU memory upper bound (I used V100 GPU), max channels...
> **IT IS PROVIDED AS IS WITH.**
> 
> Sorry for the inconvenience.
> 
> Best,
> Jun

thank
